# Generated by Django 5.2 on 2026-04-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_user_username_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('warning_percentage', models.PositiveIntegerField(default=80)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_goal', to='accounts.user')),
            ],
        ),
    ]
