# Generated by Django 5.2 on 2026-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterusage',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waterusage',
            name='activity',
            field=models.CharField(choices=[('shower', 'Shower'), ('bath', 'Bath'), ('dishwashing', 'Dishwashing'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning'), ('cooking', 'Cooking'), ('drinking', 'Drinking'), ('garden', 'Garden Watering'), ('other', 'Other')], max_length=50),
        ),
    ]
