# Generated by Django 5.2 on 2026-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_waterusage_duration_minutes_waterusage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterusage',
            name='dishwashing_method',
            field=models.CharField(blank=True, choices=[('hand', 'Hand Wash'), ('dishwasher', 'Dishwasher')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='garden_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='laundry_load_size',
            field=models.CharField(blank=True, choices=[('small', 'Small Load'), ('medium', 'Medium Load'), ('large', 'Large Load')], max_length=10, null=True),
        ),
    ]
