# Generated by Django 5.2 on 2026-04-19 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_first_name_user_last_name'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-unlocked_at'], 'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='usergameprofile',
            options={'verbose_name': 'User Game Profile', 'verbose_name_plural': 'User Game Profiles'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='rule_value',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='eco_points',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='longest_streak',
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp showing when the badge was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='last_played_date',
            field=models.DateField(blank=True, help_text='The last date the user completed the mini game.', null=True),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Current level based on accumulated eco points.'),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Total eco points earned by the user.'),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive days the user has engaged with HydroGuard.'),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent profile update.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(help_text='Short explanation of how the badge is earned.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon or emoji label for UI display.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Unique name of the badge.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(help_text='The badge unlocked by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='gamification.badge'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp showing when the badge was unlocked.'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(help_text='The user who unlocked the badge.', on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='usergameprofile',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this gamification profile.', on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='DailyGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField(default=django.utils.timezone.now, help_text='The calendar date on which the game was played.')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers achieved in the game.')),
                ('total_questions', models.PositiveIntegerField(default=3, help_text='Total number of questions shown in the mini game.')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points awarded to the user for this game session.')),
                ('completed', models.BooleanField(default=False, help_text='Indicates whether the user fully completed the daily game.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp showing when the game session was recorded.')),
                ('user', models.ForeignKey(help_text='The user who played the mini game.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_game_sessions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Daily Game Session',
                'verbose_name_plural': 'Daily Game Sessions',
                'ordering': ['-play_date'],
                'unique_together': {('user', 'play_date')},
            },
        ),
    ]
