# Generated by Django 5.2 on 2026-04-19 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_first_name_user_last_name'),
        ('gamification', '0002_alter_badge_options_alter_userbadge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_key', models.CharField(choices=[('short_shower', 'Short Shower'), ('turn_off_tap', 'Turn Off Tap'), ('smart_dishwashing', 'Smart Dishwashing'), ('log_usage', 'Log Usage')], help_text='Internal key representing the completed daily mission.', max_length=50)),
                ('play_date', models.DateField(default=django.utils.timezone.now, help_text='The date on which the mission was completed.')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points awarded for this mission completion.')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp showing when the mission was completed.')),
                ('user', models.ForeignKey(help_text='The user who completed the mission.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_mission_completions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Daily Mission Completion',
                'verbose_name_plural': 'Daily Mission Completions',
                'ordering': ['-play_date', '-completed_at'],
                'unique_together': {('user', 'mission_key', 'play_date')},
            },
        ),
    ]
